# Create a new user
POST http://localhost:4000/api/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "user34@nffoooo.local",
  "dateBirth": "2012-02-12",
  "firstname": "Keks",
  "lastname": "Smith",
  "password": "123456"
}

###

# Login user by email and password
POST http://localhost:4000/api/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@nffoooo.local",
  "password": "123456"
}

###

# Get new JWT pair
POST http://localhost:4000/api/users/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDUyMDkzMDExYmI2MzU2NTk5OTdhYzIiLCJlbWFpbCI6InVzZXJAbmZmb29vby5sb2NhbCIsInJvbGUiOiJ1c2VyIiwibGFzdG5hbWUiOiJTbWl0aCIsImZpcnN0bmFtZSI6Iktla3MiLCJ0b2tlbklkIjoiYWQ3OWNjYTctOWQ0MC00NTkwLTg3ZTUtMGU2MTQ5NzdlNWNiIiwiaWF0IjoxNjgzMTA2NDI1LCJleHAiOjE2ODU2OTg0MjV9.0dKrN3_6gKih69aexc35_GTLws_bjVuTyDmSMSpFGNI

###

# Create a new post
POST http://localhost:4000/api/blog HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDUyMDkzMDExYmI2MzU2NTk5OTdhYzIiLCJlbWFpbCI6InVzZXJAbmZmb29vby5sb2NhbCIsInJvbGUiOiJ1c2VyIiwibGFzdG5hbWUiOiJTbWl0aCIsImZpcnN0bmFtZSI6Iktla3MiLCJpYXQiOjE2ODMxODYxNTUsImV4cCI6MTY4MzE4Njc1NX0.TYYu_KFlpuwdih6QoKQfyt7_KGrJviUWZvSDRBz30sI
Content-Type: application/json

{
  "postType": "video",
  "videoPost": {
    "title": "its some leettesrand little more name1",
    "linkVideo": "https://www.youtube.com/watch?v=NYGL4hxPuxs"
  },
  "userId": "13",
  "tags": [1,1]
}
###
