# Create a new user
POST http://localhost:4000/api/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "uer64@ffooo.loal",
  "dateBirth": "2012-02-12",
  "firstname": "Keks",
  "lastname": "Smith",
  "password": "123456"
}
###
# Login user by email and password
POST http://localhost:4000/api/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@nffoooo.local",
  "password": "123555456"
}
###
# Get new JWT pair
POST http://localhost:4000/api/users/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDUyMDkzMDExYmI2MzU2NTk5OTdhYzIiLCJlbWFpbCI6InVzZXJAbmZmb29vby5sb2NhbCIsInJvbGUiOiJ1c2VyIiwibGFzdG5hbWUiOiJTbWl0aCIsImZpcnN0bmFtZSI6Iktla3MiLCJ0b2tlbklkIjoiYWQ3OWNjYTctOWQ0MC00NTkwLTg3ZTUtMGU2MTQ5NzdlNWNiIiwiaWF0IjoxNjgzMTA2NDI1LCJleHAiOjE2ODU2OTg0MjV9.0dKrN3_6gKih69aexc35_GTLws_bjVuTyDmSMSpFGNI
###
# Check user token
POST http://localhost:4000/api/users/check HTTP/1.1
Authorization: Bearer
###
# Change pass
POST http://localhost:4000/api/users/changepassword HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDUyMDkzMDExYmI2MzU2NTk5OTdhYzIiLCJlbWFpbCI6InVzZXJAbmZmb29vby5sb2NhbCIsInJvbGUiOiJ1c2VyIiwibGFzdG5hbWUiOiJTbWl0aCIsImZpcnN0bmFtZSI6Iktla3MiLCJpYXQiOjE2ODM1NzI3OTcsImV4cCI6MTY4MzU3MzM5N30.np6A7ITcfFARNiG0vaXLl1XykmrFtNVh6T-jnmiLTic
Content-Type: application/json

{
  "oldPassword": "123456",
  "newPassword": "123555456"
}
###
# Subsribe to user
POST http://localhost:4000/api/users/subcribe/6448da56b391d4e47be9ef28 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDVhMDIxYWNlZDc1NDQ2YzNiYWMxZWQiLCJlbWFpbCI6InVzZXI2NEBmZm9vby5sb2FsIiwicm9sZSI6InVzZXIiLCJsYXN0bmFtZSI6IlNtaXRoIiwiZmlyc3RuYW1lIjoiS2VrcyIsImlhdCI6MTY4MzYyMDQzNywiZXhwIjoxNjgzNjIxMDM3fQ.nI0A08pKBrChaHMaEfzYKBz7DTAvODCd59lDWBpP9lw

# Unsubsribe from user
POST http://localhost:4000/api/users/unsubcribe/6448cbf2f69083362a2ab69d HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDUyMDkzMDExYmI2MzU2NTk5OTdhYzIiLCJlbWFpbCI6InVzZXJAbmZmb29vby5sb2NhbCIsInJvbGUiOiJ1c2VyIiwibGFzdG5hbWUiOiJTbWl0aCIsImZpcnN0bmFtZSI6Iktla3MiLCJpYXQiOjE2ODMzNzA4NjAsImV4cCI6MTY4MzM3MTQ2MH0.dwdn2BFdS6bbJ5dF0SuJ3Cd_WAA9uLXtEwOkKuBqzrY
####
# Create a new post
POST http://localhost:4000/api/blog HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDUyMDkzMDExYmI2MzU2NTk5OTdhYzIiLCJlbWFpbCI6InVzZXJAbmZmb29vby5sb2NhbCIsInJvbGUiOiJ1c2VyIiwibGFzdG5hbWUiOiJTbWl0aCIsImZpcnN0bmFtZSI6Iktla3MiLCJpYXQiOjE2ODM3OTY2NjMsImV4cCI6MTY4Mzc5NzI2M30.Q6zUfizRkMlyVvGN_GGRGBKQKRKKk2FHaG7aSUegatw
Content-Type: application/json

{
  "postType": "video",
  "videoPost": {
    "title": "its some leettesrand little more name1",
    "linkVideo": "https://www.youtube.com/watch?v=NYGL4hxPuxs"
  },
  "tags": [1,1]
}
###
# Get post by id
GET http://localhost:4000/api/blog/34 HTTP/1.1

###
# Get all posts
GET http://localhost:4000/api/blog?sortType=byComments HTTP/1.1
###
# Get user posts feed
GET http://localhost:4000/api/blog/feed?sortType=byComments HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDUyMDkzMDExYmI2MzU2NTk5OTdhYzIiLCJlbWFpbCI6InVzZXJAbmZmb29vby5sb2NhbCIsInJvbGUiOiJ1c2VyIiwibGFzdG5hbWUiOiJTbWl0aCIsImZpcnN0bmFtZSI6Iktla3MiLCJpYXQiOjE2ODM2MTI5MzIsImV4cCI6MTY4MzYxMzUzMn0.GDRmcJML_MvFA1zQGv2G292kg5Xu5icUQqm1VtrU5iI
###
# Update posr by id
PATCH http://localhost:4000/api/blog/37 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDVhMDIxYWNlZDc1NDQ2YzNiYWMxZWQiLCJlbWFpbCI6InVzZXI2NEBmZm9vby5sb2FsIiwicm9sZSI6InVzZXIiLCJsYXN0bmFtZSI6IlNtaXRoIiwiZmlyc3RuYW1lIjoiS2VrcyIsImlhdCI6MTY4Mzc5MzUxMiwiZXhwIjoxNjgzNzk0MTEyfQ.Yi7xcXp_AgESyKcQZcsnH85rk3oYmW25x9a7-S-DX6U
Content-Type: application/json

{
  "videoPost": {
    "title": "UPDATED!!its some leettesrand little more name1",
    "linkVideo": "https://www.youtube.com/watch?v=NYGL4hxPuxs"}
}
###
# Find by tags
POST http://localhost:4000/api/blog/findbytags HTTP/1.1
Content-Type: application/json

{
  "tags": ["videoTag"]
}
###
# Find by text
POST http://localhost:4000/api/blog/findbytext?searchingText=sofe HTTP/1.1
###
# Repost the post
POST http://localhost:4000/api/blog/repost/34 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDUyMDkzMDExYmI2MzU2NTk5OTdhYzIiLCJlbWFpbCI6InVzZXJAbmZmb29vby5sb2NhbCIsInJvbGUiOiJ1c2VyIiwibGFzdG5hbWUiOiJTbWl0aCIsImZpcnN0bmFtZSI6Iktla3MiLCJpYXQiOjE2ODM0NDkyNjQsImV4cCI6MTY4MzQ0OTg2NH0.ILXlEpoxGiaIvh8JG6wh1K52_tKoMDw5BjGEGLVgwcM
###

# Delete the post by id
DELETE http://localhost:4000/api/blog/47 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDUyMDkzMDExYmI2MzU2NTk5OTdhYzIiLCJlbWFpbCI6InVzZXJAbmZmb29vby5sb2NhbCIsInJvbGUiOiJ1c2VyIiwibGFzdG5hbWUiOiJTbWl0aCIsImZpcnN0bmFtZSI6Iktla3MiLCJpYXQiOjE2ODM3OTY2NjMsImV4cCI6MTY4Mzc5NzI2M30.Q6zUfizRkMlyVvGN_GGRGBKQKRKKk2FHaG7aSUegatw
###

# Create a new comment
POST http://localhost:4000/api/blog/comment HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDUyMDkzMDExYmI2MzU2NTk5OTdhYzIiLCJlbWFpbCI6InVzZXJAbmZmb29vby5sb2NhbCIsInJvbGUiOiJ1c2VyIiwibGFzdG5hbWUiOiJTbWl0aCIsImZpcnN0bmFtZSI6Iktla3MiLCJpYXQiOjE2ODMzNzYyOTcsImV4cCI6MTY4MzM3Njg5N30.h9zpy3lOOQbNnQ24chk7FNM8L3pUwUC4uTemujDyfbg
Content-Type: application/json

{
  "message": "BFFmore messagesmore messagesmore messagesmore messages",
  "postId": 34
}
###

# Delete the comment by id
DELETE http://localhost:4000/api/blog/comment/6 HTTP/1.1
Authorization: Bearer
###

# # Get comment by id
# GET http://localhost:4000/api/blog/comment/6 HTTP/1.1

# ###

# Get comments by postId
GET http://localhost:4000/api/blog/comment/34?limit=5&page=2 HTTP/1.1

###
