version: '3.8'
services:

  readme.users.mongodb:
    image: mongo:latest
    container_name: readme.users.mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: readme-users
    volumes:
      - ~/db/readme.users.volume:/data/db
    networks:
      - readme.network

  readme.users:
    container_name: readme.users
    depends_on:
      - readme.users.mongodb
    restart: always
    image: readme.users:latest
    environment:
      PORT: 3000
      RABBIT_HOST: readme.notify.rabbitmq
      RABBIT_PASSWORD: test
      RABBIT_PORT: 5672
      RABBIT_USER: admin
      RABBIT_QUEUE: readme.notify
      RABBIT_EXCHANGE: readme.notify
      JWT_AT_SECRET: Secret
      JWT_AT_EXPIRES_IN: 10m
      JW_RT_SECRET: refreshTokenSecre
      JW_RT_EXPIRES_IN : 30d
      MONGO_DB: readme-users
      MONGO_HOST: readme.users.mongodb
      MONGO_PORT: 27017
      MONGO_USER: admin
      MONGO_PASSWORD: test
      MONGO_AUTH_BASE: admin
    ports:
      - 3000:3000
    networks:
      - readme.network

  readme.user.mongo.ui:
    image: mongo-express
    restart: always
    container_name: readme.user.mongo.ui
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@readme.users.mongodb:27017/
    networks:
      - readme.network

networks:
  readme.network:
    external:
      name: readme.network
  #  driver: bridge

volumes:
  readme.users.volume:
